import Head from 'next/head'
import Image from 'next/image'
import About from './components/About';
import Hero from './components/Hero';
// import { Inter } from 'next/font/google'
import Navbar from "./components/Navbar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Suman | Portflio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
    </>
  )
}
